[book]
title = "eIDAS 2.0 (UIB)"
authors = ["Miquel A. Cabot"]
description = "Documentació sobre el funcionament d'eIDAS 2.0 (UIB)"
language = "ca"
src = "content"

[build]
build-dir = "html-book"
create-missing = false # opt out of helper to create missing stub files, we want to fail if the SUMMARY is incorrect.

[rust]
edition = "2021"

[output.html]
site-url = "/eidas/" # needed for gh-pages, MUST match repo name on github!
git-repository-url = "https://github.com/uib-eidas/book"
edit-url-template = "https://github.com/uib-eidas/book/edit/main/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
